#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'
module Lrama
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 117)

def initialize(text)
  @text = text
end

def parse
  @status = :initial
  @lexer = Lrama::NewLexer.new(@text)
  @grammar = Lrama::Grammar.new
  @precedence_number = 0
  do_parse
  @grammar.extract_references
  @grammar.prepare
  @grammar.compute_nullable
  @grammar.validate!
  @grammar
end

def next_token
  case @status
  when :initial
    @lexer.lex_token
  when :c_declaration
    @lexer.lex_c_code
  end
end

private

def build_token(type:, s_value:, line:, column:, alias_name: nil)
  token_type = Lrama::Lexer::Token.const_get(type)
  token = Lrama::Lexer::Token.new(type: token_type, s_value: s_value)
  token.line = line
  token.column = column
  token.alias = alias_name

  token
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    79,   132,   113,   132,     6,   130,    55,     7,    33,    34,
    60,     3,    33,    34,    73,    33,    34,    33,    34,   133,
   129,   133,    78,   112,    65,     8,    33,    34,    31,    80,
    20,    22,    23,    24,    25,    26,    27,    28,    29,     9,
    40,    33,    34,    14,    43,    12,    45,    13,    15,    16,
    17,    18,    33,    34,    19,    20,    22,    23,    24,    25,
    26,    27,    28,    29,    20,    22,    23,    24,    25,    26,
    27,    28,    29,    33,    34,    33,    34,    65,    45,    33,
    34,    65,    45,    33,    34,   151,    48,    33,    34,   151,
    49,    33,    34,   151,    50,    33,    34,   151,    51,    33,
    34,   151,    52,    33,    34,   151,    70,    33,    34,    33,
    34,    33,    34,    33,    34,    33,    34,    33,    34,    33,
    34,    33,    34,    33,    34,    33,    34,    33,    34,    33,
    34,    33,    34,    33,    34,    33,    34,    33,    34,    74,
    76,    81,    81,    81,    88,    92,    93,    96,    96,    96,
   101,   102,   104,   105,   106,   107,   108,   109,   116,   117,
   120,   121,   122,   136,   137,   138,   139,   140,   141,   120,
    76,   146,   147,   154,   158,   159,    76,    76 ]

racc_action_check = [
    41,   119,    91,   142,     2,   118,    25,     2,    25,    25,
    26,     1,    26,    26,    32,   119,   119,   142,   142,   119,
   118,   142,    41,    91,    27,     3,    27,    27,     7,    41,
    32,    32,    32,    32,    32,    32,    32,    32,    32,     4,
    12,    32,    32,     4,    14,     4,    15,     4,     4,     4,
     4,     4,    13,    13,     4,     4,     4,     4,     4,     4,
     4,     4,     4,     4,     9,     9,     9,     9,     9,     9,
     9,     9,     9,    54,    54,     9,     9,    28,    16,    28,
    28,    29,    17,    29,    29,   139,    18,   139,   139,   140,
    20,   140,   140,   141,    22,   141,   141,   148,    23,   148,
   148,   152,    24,   152,   152,   153,    30,   153,   153,    55,
    55,    59,    59,    60,    60,    64,    64,    65,    65,    88,
    88,    90,    90,    93,    93,    95,    95,    96,    96,    98,
    98,   110,   110,   114,   114,   115,   115,   133,   133,    37,
    38,    44,    46,    47,    53,    57,    58,    63,    68,    69,
    75,    76,    82,    83,    84,    85,    86,    87,    99,   100,
   101,   102,   103,   123,   124,   125,   126,   127,   128,   129,
   131,   134,   135,   144,   155,   157,   158,   159 ]

racc_action_pointer = [
   nil,    11,     1,    25,    37,   nil,   nil,    21,   nil,    46,
   nil,   nil,    31,    23,    37,    31,    63,    67,    71,   nil,
    75,   nil,    79,    83,    87,   -21,   -17,    -3,    50,    54,
   102,   nil,    12,   nil,   nil,   nil,   nil,   122,   106,   nil,
   nil,    -7,   nil,   nil,   126,   nil,   127,   128,   nil,   nil,
   nil,   nil,   nil,   117,    44,    80,   nil,   136,   119,    82,
    84,   nil,   nil,   120,    86,    88,   nil,   nil,   121,   122,
   nil,   nil,   nil,   nil,   nil,   119,   122,   nil,   nil,   nil,
   nil,   nil,   148,   149,   150,   151,   152,   153,    90,   nil,
    92,    -5,   nil,    94,   nil,    96,    98,   nil,   100,   153,
   155,   145,   126,   158,   nil,   nil,   nil,   nil,   nil,   nil,
   102,   nil,   nil,   nil,   104,   106,   nil,   nil,   -12,   -14,
   nil,   nil,   nil,   147,   148,   149,   150,   151,   152,   154,
   nil,   136,   nil,   108,   167,   156,   nil,   nil,   nil,    58,
    62,    66,   -12,   nil,   169,   nil,   nil,   nil,    70,   nil,
   nil,   nil,    74,    78,   nil,   158,   nil,   159,   142,   143,
   nil,   nil ]

racc_action_default = [
    -2,  -102,    -8,  -102,  -102,    -3,    -4,  -102,   162,  -102,
    -9,   -10,  -102,  -102,  -102,  -102,  -102,  -102,  -102,   -20,
  -102,   -24,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,
  -102,    -7,   -90,   -68,   -69,   -70,   -72,  -102,   -87,   -89,
   -11,   -94,   -93,   -13,   -14,   -59,   -15,   -16,   -17,   -21,
   -25,   -28,   -31,   -34,   -39,  -102,   -42,   -45,   -35,   -50,
  -102,   -53,   -55,   -36,   -62,  -102,   -65,   -67,   -37,   -38,
    -5,    -1,   -71,   -91,   -73,  -102,  -102,   -12,   -95,   -96,
   -97,   -56,  -102,  -102,  -102,  -102,  -102,  -102,  -102,   -43,
   -40,   -47,   -46,  -102,   -54,   -51,  -102,   -66,   -63,  -102,
  -102,   -78,  -102,  -102,   -60,   -18,   -22,   -26,   -29,   -32,
   -41,   -44,   -48,   -49,   -52,   -64,    -6,   -92,   -74,   -75,
   -83,   -88,   -57,  -102,  -102,  -102,  -102,  -102,  -102,   -78,
   -77,   -87,   -80,  -102,  -102,  -102,   -61,   -19,   -23,  -102,
  -102,  -102,   -76,   -79,  -102,   -86,   -84,   -58,   -27,   -98,
  -100,  -101,   -30,   -33,   -81,  -102,   -99,  -102,   -87,   -87,
   -85,   -82 ]

racc_goto_table = [
    75,    61,    59,    39,    89,    97,    98,    42,    54,    35,
   156,     1,     2,   119,   156,   156,    44,    46,    47,    57,
     4,    67,    67,    67,    32,    71,    39,   148,   152,   153,
     5,    30,    72,    99,    94,    61,    95,   115,    90,    97,
    89,   142,    63,    68,    69,    10,    11,    41,    57,    57,
    77,    83,   124,    84,   125,    85,    97,   126,    67,    67,
    89,    86,   127,    87,   128,    53,    58,    91,    61,   114,
    94,   110,   111,   103,   135,    82,   123,   118,   144,   157,
   134,   155,    57,   100,    57,   nil,   nil,   nil,   nil,    94,
    67,   nil,    67,   143,   131,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    57,   nil,   nil,   nil,   145,    67,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   131,   nil,   nil,
   160,   161 ]

racc_goto_check = [
    45,    35,    34,    31,    30,    41,    40,    31,    29,    42,
    53,     1,     2,    47,    53,    53,    13,    13,    13,    31,
     3,    31,    31,    31,     4,     5,    31,    17,    17,    17,
     6,     7,    42,     8,    35,    35,    34,    40,    29,    41,
    30,    47,    28,    28,    28,     9,    10,    11,    31,    31,
    12,    14,    15,    18,    19,    20,    41,    21,    31,    31,
    30,    22,    23,    24,    25,    26,    27,    32,    35,    34,
    35,    29,    33,    36,    37,    38,    39,    46,    48,    49,
    50,    51,    31,    52,    31,   nil,   nil,   nil,   nil,    35,
    31,   nil,    31,    45,    35,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    31,   nil,   nil,   nil,    35,    31,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,   nil,   nil,
    45,    45 ]

racc_goto_pointer = [
   nil,    11,    12,    18,    15,    -7,    28,    25,   -37,    41,
    42,    34,     9,     1,     3,   -53,   nil,  -112,     4,   -52,
     5,   -50,    10,   -46,    11,   -45,    40,    40,    15,   -17,
   -50,    -6,    10,   -19,   -24,   -25,    -8,   -48,    30,   -28,
   -59,   -59,     0,   nil,   nil,   -38,   -24,   -88,   -54,   -75,
   -40,   -65,    10,  -138 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    37,   nil,   nil,   nil,   nil,   nil,    21,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    56,    62,   nil,   nil,   nil,   150,   nil,   nil,   nil,   nil,
    64,    66,   nil,    36,    38,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   149 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 38, :_reduce_none,
  0, 39, :_reduce_none,
  2, 39, :_reduce_none,
  0, 44, :_reduce_4,
  0, 45, :_reduce_5,
  5, 43, :_reduce_6,
  2, 43, :_reduce_none,
  0, 40, :_reduce_8,
  2, 40, :_reduce_none,
  1, 46, :_reduce_none,
  2, 46, :_reduce_none,
  3, 46, :_reduce_none,
  2, 46, :_reduce_none,
  2, 46, :_reduce_none,
  2, 46, :_reduce_15,
  2, 46, :_reduce_16,
  0, 51, :_reduce_17,
  0, 52, :_reduce_18,
  6, 46, :_reduce_19,
  1, 46, :_reduce_none,
  0, 55, :_reduce_21,
  0, 56, :_reduce_22,
  6, 47, :_reduce_23,
  1, 47, :_reduce_none,
  0, 57, :_reduce_25,
  0, 58, :_reduce_26,
  7, 47, :_reduce_none,
  0, 59, :_reduce_28,
  0, 60, :_reduce_29,
  7, 47, :_reduce_30,
  0, 61, :_reduce_31,
  0, 62, :_reduce_32,
  7, 47, :_reduce_33,
  2, 53, :_reduce_none,
  2, 53, :_reduce_35,
  2, 53, :_reduce_36,
  2, 53, :_reduce_37,
  2, 53, :_reduce_38,
  1, 63, :_reduce_39,
  2, 63, :_reduce_40,
  3, 63, :_reduce_41,
  1, 66, :_reduce_42,
  2, 66, :_reduce_43,
  3, 67, :_reduce_44,
  0, 69, :_reduce_none,
  1, 69, :_reduce_none,
  0, 70, :_reduce_none,
  1, 70, :_reduce_none,
  1, 70, :_reduce_none,
  1, 64, :_reduce_50,
  2, 64, :_reduce_51,
  3, 64, :_reduce_52,
  1, 71, :_reduce_53,
  2, 71, :_reduce_54,
  1, 72, :_reduce_none,
  0, 73, :_reduce_56,
  0, 74, :_reduce_57,
  6, 50, :_reduce_58,
  0, 75, :_reduce_59,
  0, 76, :_reduce_60,
  5, 50, :_reduce_61,
  1, 65, :_reduce_62,
  2, 65, :_reduce_63,
  3, 65, :_reduce_64,
  1, 77, :_reduce_65,
  2, 77, :_reduce_66,
  1, 78, :_reduce_none,
  1, 68, :_reduce_none,
  1, 68, :_reduce_none,
  1, 41, :_reduce_none,
  2, 41, :_reduce_none,
  1, 79, :_reduce_none,
  2, 79, :_reduce_none,
  4, 80, :_reduce_74,
  1, 83, :_reduce_75,
  3, 83, :_reduce_76,
  2, 83, :_reduce_none,
  0, 84, :_reduce_78,
  3, 84, :_reduce_79,
  0, 85, :_reduce_80,
  0, 86, :_reduce_81,
  7, 84, :_reduce_82,
  0, 87, :_reduce_83,
  0, 88, :_reduce_84,
  6, 84, :_reduce_85,
  3, 84, :_reduce_86,
  0, 82, :_reduce_none,
  3, 82, :_reduce_88,
  1, 81, :_reduce_none,
  0, 42, :_reduce_none,
  0, 89, :_reduce_91,
  3, 42, :_reduce_92,
  1, 48, :_reduce_none,
  0, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 54, :_reduce_98,
  2, 54, :_reduce_99,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none ]

racc_reduce_n = 102

racc_shift_n = 162

racc_token_table = {
  false => 0,
  :error => 1,
  "%%" => 2,
  "%{" => 3,
  :C_DECLARATION => 4,
  "%}" => 5,
  "%require" => 6,
  :STRING => 7,
  "%expect" => 8,
  :INTEGER => 9,
  "%define" => 10,
  "%param" => 11,
  "%lex-param" => 12,
  "%parse-param" => 13,
  "%initial-action" => 14,
  "{" => 15,
  "}" => 16,
  ";" => 17,
  "%union" => 18,
  "%destructor" => 19,
  "%printer" => 20,
  "%error-token" => 21,
  "%token" => 22,
  "%type" => 23,
  "%left" => 24,
  "%right" => 25,
  "%nonassoc" => 26,
  :TAG => 27,
  :string_as_id => 28,
  :IDENTIFIER => 29,
  :CHARACTER => 30,
  ":" => 31,
  "|" => 32,
  "%prec" => 33,
  "[" => 34,
  "]" => 35,
  "{...}" => 36 }

racc_nt_base = 37

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"%%\"",
  "\"%{\"",
  "C_DECLARATION",
  "\"%}\"",
  "\"%require\"",
  "STRING",
  "\"%expect\"",
  "INTEGER",
  "\"%define\"",
  "\"%param\"",
  "\"%lex-param\"",
  "\"%parse-param\"",
  "\"%initial-action\"",
  "\"{\"",
  "\"}\"",
  "\";\"",
  "\"%union\"",
  "\"%destructor\"",
  "\"%printer\"",
  "\"%error-token\"",
  "\"%token\"",
  "\"%type\"",
  "\"%left\"",
  "\"%right\"",
  "\"%nonassoc\"",
  "TAG",
  "string_as_id",
  "IDENTIFIER",
  "CHARACTER",
  "\":\"",
  "\"|\"",
  "\"%prec\"",
  "\"[\"",
  "\"]\"",
  "\"{...}\"",
  "$start",
  "input",
  "prologue_declarations",
  "bison_declarations",
  "grammar",
  "epilogue_opt",
  "prologue_declaration",
  "@1",
  "@2",
  "bison_declaration",
  "grammar_declaration",
  "variable",
  "value",
  "params",
  "@3",
  "@4",
  "symbol_declaration",
  "generic_symlist",
  "@5",
  "@6",
  "@7",
  "@8",
  "@9",
  "@10",
  "@11",
  "@12",
  "token_declarations",
  "symbol_declarations",
  "token_declarations_for_precedence",
  "token_declaration_list",
  "token_declaration",
  "id",
  "int_opt",
  "alias",
  "symbol_declaration_list",
  "symbol",
  "@13",
  "@14",
  "@15",
  "@16",
  "token_declaration_list_for_precedence",
  "token_declaration_for_precedence",
  "rules_or_grammar_declaration",
  "rules",
  "id_colon",
  "named_ref_opt",
  "rhs_list",
  "rhs",
  "@17",
  "@18",
  "@19",
  "@20",
  "@21",
  "generic_symlist_item" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_4(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '%}'; @grammar.prologue_first_lineno = @lexer.line
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_5(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_6(val, _values, result)
     @grammar.prologue = val[2].s_value
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_8(val, _values, result)
     result = ""
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_15(val, _values, result)
     val[1].each {|token| token.references = []; @grammar.lex_param = @grammar.build_code(:lex_param, token).token_code.s_value}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_16(val, _values, result)
     val[1].each {|token| token.references = []; @grammar.parse_param = @grammar.build_code(:parse_param, token).token_code.s_value}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_17(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_18(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_19(val, _values, result)
     @grammar.initial_action = @grammar.build_code(:initial_action, val[3])
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_21(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_22(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_23(val, _values, result)
     @grammar.set_union(@grammar.build_code(:union, val[3]), val[3].line)
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_25(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_26(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_28(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_29(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_30(val, _values, result)
     @grammar.add_printer(ident_or_tags: val[6], code: @grammar.build_code(:printer, val[3]), lineno: val[3].line)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_31(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_32(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_33(val, _values, result)
     @grammar.add_error_token(ident_or_tags: val[6], code: @grammar.build_code(:error_token, val[3]), lineno: val[3].line)
    result
  end
.,.,

# reduce 34 omitted

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_35(val, _values, result)
     val[1].each {|hash| hash[:tokens].each {|id| @grammar.add_type(id: id, tag: hash[:tag]) } }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_36(val, _values, result)
     val[1].each {|hash| hash[:tokens].each {|id| sym = @grammar.add_term(id: id); @grammar.add_left(sym, @precedence_number) } }; @precedence_number += 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_37(val, _values, result)
     val[1].each {|hash| hash[:tokens].each {|id| sym = @grammar.add_term(id: id); @grammar.add_right(sym, @precedence_number) } }; @precedence_number += 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_38(val, _values, result)
     val[1].each {|hash| hash[:tokens].each {|id| sym = @grammar.add_term(id: id); @grammar.add_nonassoc(sym, @precedence_number) } }; @precedence_number += 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_39(val, _values, result)
     val[0].each {|token_declaration| @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: nil, replace: true) }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_40(val, _values, result)
     val[1].each {|token_declaration| @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[0], replace: true) }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_41(val, _values, result)
     val[2].each {|token_declaration| @grammar.add_term(id: token_declaration[0], alias_name: token_declaration[2], token_id: token_declaration[1], tag: val[1], replace: true) }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_42(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_43(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 42)
  def _reduce_44(val, _values, result)
     result = val
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_50(val, _values, result)
     result = [{tag: nil, tokens: val[0]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_51(val, _values, result)
     result = [{tag: val[0], tokens: val[1]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_52(val, _values, result)
     result = val[0].append({tag: val[1], tokens: val[2]})
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 55)
  def _reduce_53(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_54(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 55 omitted

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_56(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_57(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_58(val, _values, result)
     result = val[0].append(val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_59(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_60(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 61)
  def _reduce_61(val, _values, result)
     result = [val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_62(val, _values, result)
     result = [{tag: nil, tokens: val[0]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_63(val, _values, result)
     result = [{tag: val[0], tokens: val[1]}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_64(val, _values, result)
     result = val[0].append({tag: val[1], tokens: val[1]})
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_65(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_66(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_74(val, _values, result)
     lhs = val[0]; lhs.alias = val[1]; val[3].each {|hash| @grammar.add_rule(lhs: lhs, rhs: hash[:rhs], lineno: hash[:lineno]) }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_75(val, _values, result)
     result = [{rhs: val[0], lineno: val[0].first&.line || @lexer.line}]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_76(val, _values, result)
     result = val[0].append({rhs: val[2], lineno: val[2].first&.line || @lexer.line})
    result
  end
.,.,

# reduce 77 omitted

module_eval(<<'.,.,', 'parser.y', 87)
  def _reduce_78(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 88)
  def _reduce_79(val, _values, result)
     token = val[1]; val[1].alias = val[2]; result = val[0].append(token)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_80(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_81(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_82(val, _values, result)
     token = val[3]; token.alias = val[6]; result = val[0].append(token)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_83(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '}'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_84(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_85(val, _values, result)
     token = val[2]; token.alias = val[5]; result = [token]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_86(val, _values, result)
     sym = @grammar.find_symbol_by_id!(val[2]); result = val[0].append(sym)
    result
  end
.,.,

# reduce 87 omitted

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_88(val, _values, result)
     result = val[1].s_value
    result
  end
.,.,

# reduce 89 omitted

# reduce 90 omitted

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_91(val, _values, result)
    @status = :c_declaration; @lexer.end_symbol = '\Z'; @grammar.epilogue_first_lineno = @lexer.line + 1
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_92(val, _values, result)
    @status = :initial; @lexer.end_symbol = nil; @grammar.epilogue = val[2].s_value
    result
  end
.,.,

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_98(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_99(val, _values, result)
     result = val[0].append(val[1])
    result
  end
.,.,

# reduce 100 omitted

# reduce 101 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Lrama
